services:
  # Database services
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=testuser
      - MONGO_INITDB_ROOT_PASSWORD=test1234
    networks:
      - api-network

  # Kong API Gateway (DB-less mode)
  kong:
    image: kong:3.4.2
    container_name: kong
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - KONG_DATABASE=off
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml
      - KONG_PLUGINS=bundled,jwt,cors,rate-limiting,request-transformer,jwt-claims-headers
      - KONG_LUA_PACKAGE_PATH=/kong/plugins/?.lua;;
      - KONG_LOG_LEVEL=debug
    volumes:
      - ./api-gateway-kong/kong.yml:/kong/declarative/kong.yml:ro
      - ./kong-plugins:/kong/plugins:ro
    ports:
      - "8000:8000"  # Kong proxy port
      - "8001:8001"  # Kong admin API port
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    networks:
      - api-network

volumes:
  mongodb_data:
    driver: local

networks:
  api-network:
    driver: bridge
